# Generated by Django 4.2.6 on 2024-04-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('userpassword', models.CharField(max_length=200)),
                ('usernumber', models.CharField(max_length=20)),
                ('useremail', models.EmailField(max_length=254)),
                ('playerclass', models.TextField()),
            ],
        ),
    ]
